---
title: "RNA report"
subtitle: "Rapid Needs Assessment Syria"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    output_file: "RNA_Output_Dec_2024.html"
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: true
      smooth_scroll: false
    df_print: paged
    fig_caption: yes
    css: "updated_style.css"
editor_options:
  markdown:
    wrap: sentence
---

<!-- set the buttons -->
<div style="text-align: center; margin-top: 20px;">
  <a href="#All" class="button">All</a>
  <a href="#subdistrict" class="button">Sub-District Aggregation</a>
  <a href="#district" class="button">District Aggregation</a>
</div>

# All {#All}

## Demographic

## Education

## FLS

## WASH

# Sub-District Aggregation {#subdistrict}

## Demographic

## Education

## FLS

## WASH


# District Aggregation {#district}

## Demographic

## Education

## FLS

## WASH


```{r setup, include=FALSE}
library(readxl)
library(dplyr)
library(stringr)
library(ggplot2)
library(knitr)
library(kableExtra)

source("./scripts/functions.R")
``` 


```{r, echo=F, results='hide', message=FALSE}
htmltools::img(src = knitr::image_uri("./inputs/logos/reach.jpg"),
               alt = 'logo',
               style = 'position:absolute;
                        top:0; 
                        right:0; padding:10px; width: 350px; height: auto;')
```

```{r, include=FALSE, message=FALSE}
rna_assessment <- read_excel("./inputs/data/analysis_outputs_rna.xlsx")
message("Variables and Data successfully loaded.")
```

```{r, echo=FALSE}
# read the data from the excel file
data = rna_assessment %>% select(analysis_type, analysis_var, analysis_var_value, group_var, group_var_value, stat, n, section, label)

# aggregate the data by group_var
# overall 
data_overall <- data %>% 
    filter(is.na(group_var) | group_var == "") %>%
    mutate(group_var_value = "Overall") %>%
    select(-group_var)
# district
data_district <- data %>%
  filter(str_detect(group_var, "Qmeta8_District")) %>%
  select(-group_var)
# subdistrict
data_subdistrict <- data %>%
  filter(str_detect(group_var, "Qmeta9_SubDistrict")) %>%
  select(-group_var)
```

```{r, echo=FALSE, results='asis'}

# Generate a table for prop_select_multiple
filtered_data <- data_district %>%
    filter(
      analysis_type == "prop_select_multiple",
      analysis_var == "Qaap1_How_Do_People_Here_Prefer_To_Receive_Information",  # Filtra per analysis_var
      group_var_value == "Al Bab"  # Filtra per valore di group_var_value
    ) %>%
    mutate(stat = round(stat*100, 1)) %>%  # Moltiplica per 100 e arrotonda a 1 decimale
    select(analysis_var_value, label, stat, n)  # Mostra solo analysis_var_value e stat

  # Crea la tabella
  kable(
    filtered_data,
    caption = paste("Table for prop_select_multiple - Group Value:", "Al Bab"),
    col.names = c("Option", "Label", "%", "N of Responses"),
    format = "html"
  ) %>%
  kable_minimal(
    html_font = "\"Raleway\", raleway, Segoe UI Light, sans-serif"  # Apply font styling
  )
```

```{r, echo=FALSE, results='asis'}
# Generate a table for prop_select_multiple
filtered_data_2 <- data_district %>%
    filter(
      analysis_type == "prop_select_one",
      group_var_value == "Afrin",
      section == "Demographic",
      label == "Key informant type"
    ) %>%
    mutate(stat = round(stat*100, 1)) %>%  # Moltiplica per 100 e arrotonda a 1 decimale
    select(analysis_var_value, stat, n)  # Mostra solo analysis_var_value e stat
  print(filtered_data_2)
  # Crea la tabella
  kable(
    filtered_data_2,
    caption = paste("Table for prop_select_one - District; Afrin - Section:", "Demographic" , "- Label:", "Key Informant Type"),
    col.names = c("Analysis_var_value", "%", "N of Responses"),
    format = "html"
  ) %>%
  kable_minimal(
    html_font = "\"Raleway\", raleway, Segoe UI Light, sans-serif"  # Apply font styling
  )
```